In [3]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [4]:
data = {"Car": ["BMW", "ALTO", "AUDI","MARUTI", "HONDA", "HYUNDAI", "FORD", "KIA"],\
     "Color": ["Red", "Yellow", "Black", "Green", "Black", "Red", "Black", "Black"],\
     "Year": ["1990", "1980", "2003", "2000", "2001", "2004", "1999", "2020"],\
     "Rating": ["2.5", "1.5", "3.8", "9.7", "8.9", "3.2", "5.5", "6.9"],\
     "Date": ["30/04/2023", "31/08/1999", "28/12/2015", "29/06/2011",\
                 "30/12/2020", "31/07/2013", "28/11/2000", "25/12/2020"]}
df = pd.DataFrame(data)
df

       Car   Color  Year Rating        Date
0      BMW     Red  1990    2.5  30/04/2023
1     ALTO  Yellow  1980    1.5  31/08/1999
2     AUDI   Black  2003    3.8  28/12/2015
3   MARUTI   Green  2000    9.7  29/06/2011
4    HONDA   Black  2001    8.9  30/12/2020
5  HYUNDAI     Red  2004    3.2  31/07/2013
6     FORD   Black  1999    5.5  28/11/2000
7      KIA   Black  2020    6.9  25/12/2020

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Car     8 non-null      object
 1   Color   8 non-null      object
 2   Year    8 non-null      object
 3   Rating  8 non-null      object
 4   Date    8 non-null      object
dtypes: object(5)
memory usage: 452.0+ bytes

In [6]:
df["Date"] = pd.to_datetime(df["Date"])

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Car     8 non-null      object
 1   Color   8 non-null      object
 2   Year    8 non-null      object
 3   Rating  8 non-null      object
 4   Date    8 non-null      datetime64[ns]
dtypes: datetime64[ns](1), object(4)
memory usage: 452.0+ bytes

# Date Range

In [8]:
#day wise
print(pd.date_range("2000/1/11", periods = 5))

DatetimeIndex(['2000-01-11', '2000-01-12', '2000-01-13', '2000-01-14',
               '2000-01-15'],
              dtype='datetime64[ns]', freq='D')

In [9]:
#MOnth wise
print(pd.date_range("2000/1/11", periods = 5, freq = "M"))

DatetimeIndex(['2000-01-31', '2000-02-29', '2000-03-31', '2000-04-30',
               '2000-05-31'],
              dtype='datetime64[ns]', freq='ME')

In [10]:
#Year wise
print(pd.date_range("2000/1/11", periods = 5, freq = "Y"))

DatetimeIndex(['2000-12-31', '2001-12-31', '2002-12-31', '2003-12-31',
               '2004-12-31'],
              dtype='datetime64[ns]', freq='YE-DEC')

In [14]:
#create a datetime with specified intervals
start = pd.to_datetime("2011/1/1")
print("Start:",start)

end = pd.to_datetime("2011/1/20")
print("Start:",end)
print(pd.date_range(start,end))

Start: 2011-01-01 00:00:00
Start: 2011-01-20 00:00:00
DatetimeIndex(['2011-01-01', '2011-01-02', '2011-01-03', '2011-01-04',
               '2011-01-05', '2011-01-06', '2011-01-07', '2011-01-08',
               '2011-01-09', '2011-01-10', '2011-01-11', '2011-01-12',
               '2011-01-13', '2011-01-14', '2011-01-15', '2011-01-16',
               '2011-01-17', '2011-01-18', '2011-01-19', '2011-01-20'],
              dtype='datetime64[ns]', freq='D')

In [25]:
#creating dataframe with date column
df = pd.DataFrame({"name": ["Pk","RJ","YP"],
                   "DoB": ["01-02-2000","03-04-2001","05-06-2002"]})

In [26]:
df

  name         DoB
0   Pk  01-02-2000
1   RJ  03-04-2001
2   YP  05-06-2002

In [27]:
df.dtypes

name    object
DoB     object
dtype: object

In [29]:
df["DoB"] = pd.to_datetime(df["DoB"])

In [30]:
df["DoB"].dt.year

0    2000
1    2001
2    2002
Name: DoB, dtype: int32

In [31]:
#checking present year
today = pd.to_datetime("today")
today.year

2025

In [33]:
#new column on the difference year
df["Age"] = today.year - df["DoB"].dt.year
df

  name        DoB  Age
0   Pk 2000-01-02   25
1   RJ 2001-03-04   24
2   YP 2002-05-06   23

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      object
 1   DoB     3 non-null      datetime64[ns]
 2   Age     3 non-null      int32
dtypes: datetime64[ns](1), int32(1), object(1)
memory usage: 192.0+ bytes

In [46]:
df["DoB"]

0   2000-01-02
1   2001-03-04
2   2002-05-06
Name: DoB, dtype: datetime64[ns]

In [47]:
df["DoB"].dt.year #check year

0    2000
1    2001
2    2002
Name: DoB, dtype: int32

In [48]:
df["DoB"].dt.day #check day

0    2
1    4
2    6
Name: DoB, dtype: int32

In [49]:
df["DoB"].dt.month  #check day

0    1
1    3
2    5
Name: DoB, dtype: int32

In [50]:
df["DoB"].dt.day_name() #check day name

0    Sunday
1    Sunday
2    Monday
Name: DoB, dtype: object

In [51]:
df["DoB"].dt.month_name() #check month name

0    January
1      March
2        May
Name: DoB, dtype: object

In [52]:
today = pd.to_datetime("today") #check current day
today

Timestamp('2025-12-15 10:23:46.636386')

In [53]:
today = pd.to_datetime("today") #check current year
today.year

2025

In [54]:
today = pd.to_datetime("today") #check current day name
today.day_name()

'Monday'

In [55]:
today = pd.to_datetime("today") #check current month name
today.month_name()

'December'