# Duplicates

In [3]:
import pandas as pd

import warnings
warnings.filterwarnings("ignore")

In [4]:
# Creating data Frame
dict1 = {"Gender": ["Male","Female","Male","Female","Male"],
         "Married": ["Yes","No","No","No","Yes"],
         "Loan_Status":["Yes","No","No","No","Yes"]
        }
df = pd.DataFrame(dict1)
df

   Gender Married Loan_Status
0    Male     Yes         Yes
1  Female      No          No
2    Male      No          No
3  Female      No          No
4    Male     Yes         Yes

In [9]:
df.duplicated()  #give true where duplicates occurs

0    False
1    False
2    False
3     True
4     True
dtype: bool

In [10]:
df.drop_duplicates() #duplicate value droped

   Gender Married Loan_Status
0    Male     Yes         Yes
1  Female      No          No
2    Male      No          No

# Droping Duplicates from particular columns

In [11]:
df

   Gender Married Loan_Status
0    Male     Yes         Yes
1  Female      No          No
2    Male      No          No
3  Female      No          No
4    Male     Yes         Yes

In [12]:
df.drop_duplicates(["Married"])

   Gender Married Loan_Status
0    Male     Yes         Yes
1  Female      No          No

In [14]:
#with keep="first" - ,mark duplicates as true for the first one
duplicates_first = df.duplicated(keep = "first")
duplicates_first

0    False
1    False
2    False
3     True
4     True
dtype: bool

In [17]:
#with keep="last" - ,mark duplicates as true for the last one
duplicates_first = df.duplicated(keep = "last")
duplicates_first

0     True
1     True
2    False
3    False
4    False
dtype: bool

In [18]:
df

   Gender Married Loan_Status
0    Male     Yes         Yes
1  Female      No          No
2    Male      No          No
3  Female      No          No
4    Male     Yes         Yes

In [20]:
# In drop_duplicates with keep = "first" -keep duplicates which occured first time and drop others
df1 = df.drop_duplicates(keep= "first") 
df1

   Gender Married Loan_Status
0    Male     Yes         Yes
1  Female      No          No
2    Male      No          No

In [21]:
# In drop_duplicates with keep = "last" -keep duplicates which occured last time and drop others
df1 = df.drop_duplicates(keep= "last") 
df1

   Gender Married Loan_Status
2    Male      No          No
3  Female      No          No
4    Male     Yes         Yes

In [22]:
df

   Gender Married Loan_Status
0    Male     Yes         Yes
1  Female      No          No
2    Male      No          No
3  Female      No          No
4    Male     Yes         Yes

In [23]:
df.drop_duplicates(keep="first",subset=["Gender","Married"])

   Gender Married Loan_Status
0    Male     Yes         Yes
1  Female      No          No
2    Male      No          No

In [27]:
#with subset
df.drop_duplicates(keep="first",subset=["Married","Loan_Status"])

   Gender Married Loan_Status
0    Male     Yes         Yes
1  Female      No          No

In [28]:
df.drop_duplicates(keep="last",subset=["Married","Loan_Status"])

   Gender Married Loan_Status
3  Female      No          No
4    Male     Yes         Yes