# Q.1) Group the DataFrame by 'Department' and calculate the mean salary for each department.
* data = {'Employeel D': [101, 102, 103, 104, 105],
'Employee Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
'Department': ['HR', 'IT', 'HR', 'Finonlinance', 'IT'],
'Salary': [60000, 80000, 70000, 90000, 85000],
'Joining Date': [date(2018, 5, 15), date (2019, 2, 10), date(2018, 8, 22), date(2020, 1, 5), date(2019, 7,
12)]}
* Group the DataFrame by 'Department' and get the group with the highest average salary.

In [17]:
import pandas as pd
import numpy as np
import datetime
from datetime import datetime

In [18]:
#DataFrame 
data = {'Employeel D': [101, 102, 103, 104, 105],
'Employee Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
'Department': ['HR', 'IT', 'HR', 'Finonlinance', 'IT'],
'Salary': [60000, 80000, 70000, 90000, 85000],
'Joining Date': [(2018, 5, 15),(2019, 2, 10),(2018, 8, 22),(2020, 1, 5),(2019, 7,12)]}

df = pd.DataFrame(data)
df

   Employeel D Employee Name    Department  Salary   Joining Date
0          101         Alice            HR   60000  (2018, 5, 15)
1          102           Bob            IT   80000  (2019, 2, 10)
2          103       Charlie            HR   70000  (2018, 8, 22)
3          104         David  Finonlinance   90000   (2020, 1, 5)
4          105           Eva            IT   85000  (2019, 7, 12)

In [19]:
#DataFrame by 'Department' and calculate the mean salary for each department.
df.groupby("Department")[["Salary"]].mean()

               Salary
Department
Finonlinance  90000.0
HR            65000.0
IT            82500.0

In [20]:
# Group the DataFrame by 'Department' and get the group with the highest average salary.
df.groupby('Department')['Salary'].mean().idxmax()

'Finonlinance'

##
------

# Q.2) Group the DataFrame by 'Department' and create a new DataFrame that shows the count of employees in each department.
* Create a new column 'YearsInCompany' that calculates the number of years each employee has been with the company. Group the DataFrame by 'Department'    and get the group with the employee who has been with the company for the longest time.

In [21]:
# Group the DataFrame by 'Department' and create a new DataFrame that shows the count of employees in each department.(
df.groupby("Department")[["Employee Name"]].count().reset_index(names = "Employee Count")

  Employee Count  Employee Name
0   Finonlinance              1
1             HR              2
2             IT              2

In [22]:
df["Joining Date"] = df["Joining Date"].apply(lambda x: pd.Timestamp(*x))

In [23]:
df["Joining Date"] = pd.to_datetime(df["Joining Date"])
df["YearsInCompany"] = (pd.Timestamp.now() - df["Joining Date"]).dt.days // 365

In [24]:
df

,Employeel D,Employee Name,Department,Salary,Joining Date,YearsInCompany
0,101,Alice,HR,60000,2018-05-15,7
1,102,Bob,IT,80000,2019-02-10,6
2,103,Charlie,HR,70000,2018-08-22,7
3,104,David,Finonlinance,90000,2020-01-05,5
4,105,Eva,IT,85000,2019-07-12,6

In [27]:
# Group the DataFrame by 'Department' and get the group with the employee who has been with the company for the longest time.
df.groupby("Department")["YearsInCompany"].max().idxmax()

'HR'

## 
-----

# Q.3) Create a new column 'Bonus' that calculates a bonus of 15% of the salary for each employee. Group the DataFrame by 'Department' and find the department with the highest average bonus.
* Group the DataFrame by 'Department' and get the group with the employee who joined the company earliest in each department.

In [25]:
df["Bonus"] = df["Salary"] + (df["Salary"] * 0.15)
df

,Employeel D,Employee Name,Department,Salary,Joining Date,YearsInCompany,Bonus
0,101,Alice,HR,60000,2018-05-15,7,69000.0
1,102,Bob,IT,80000,2019-02-10,6,92000.0
2,103,Charlie,HR,70000,2018-08-22,7,80500.0
3,104,David,Finonlinance,90000,2020-01-05,5,103500.0
4,105,Eva,IT,85000,2019-07-12,6,97750.0

In [26]:
df.loc[df.groupby('Department')['Joining Date'].idxmin()]

,Employeel D,Employee Name,Department,Salary,Joining Date,YearsInCompany,Bonus
3,104,David,Finonlinance,90000,2020-01-05,5,103500.0
0,101,Alice,HR,60000,2018-05-15,7,69000.0
1,102,Bob,IT,80000,2019-02-10,6,92000.0